### ISSUE TITLE
shovel: reorg handling trouble

### ISSUE THREAD

**Issue by kayleegeorge** [indexsupply/shovel#271]
- using `a475` shovel version (so should be post-reorg fix in v1.5)
- polygon reorg caused shovel to halt, error deleting task_update

<img width="800" alt="Screenshot 2024-08-26 at 9 52 37 AM" src="https://github.com/user-attachments/assets/b4507ab8-1430-4bdd-b139-4e97702d13af">

<img width="800" alt="Screenshot 2024-08-26 at 9 47 53 AM" src="https://github.com/user-attachments/assets/56b9d188-fdc3-49f9-9388-d067442febc3">

**Comment by ryandotsmith** [comment]
It looks like there are 2 issues:

1) There is a reorg and as shovel attempts to delete data associated with the reorg the SQL statements are timing out. I can't  debug this without the query that is timing out. It is likely that one of the integration tables has a bunch of data in it and when shovel is deleting the data the query is timing out.

2) The corrupt chain error occurs [here](https://github.com/indexsupply/shovel/blob/064852273ce319bac57a2a2b3dad792a8aae3547/jrpc2/client.go#L604) and is typically surface when the RPC is serving incorrect data.

For issue #1 please provide more detail as described in this new issue: https://github.com/indexsupply/shovel/issues/272

I'm not sure what can be done about #2. Feel free to open a separate issue with more detail if this continues to be a problem.
